flipping_words_reversed_v1: flipping_words_reversed_v1.c
	gcc -g -O0 flipping_words_reversed_v1.c -lcriterion -o flipping_words_reversed_v1
	# -O0 and -g is an optimization (-g for the info to the debugger and -O0 for Compile with Lower Optimization to see step by step variable change in debugger)